# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-11 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_enrichment", "0001_initial"),
        ("django_enrichment", "0002_etap09_undo"),
        ("django_enrichment", "0003_spawn_rule"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpawnRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("module", models.CharField(max_length=32)),
                ("check_key", models.CharField(max_length=64)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("scope", models.JSONField(blank=True, default=dict)),
                ("task_type", models.CharField(max_length=64)),
                ("task_params", models.JSONField(blank=True, default=dict)),
                ("limit", models.PositiveIntegerField(blank=True, null=True)),
                ("cooldown_days", models.PositiveIntegerField(blank=True, null=True)),
                ("auto", models.BooleanField(db_index=True, default=False)),
                ("active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnrichmentTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(db_index=True, max_length=64)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("scope_spec", models.JSONField(blank=True, default=dict)),
                ("batch_key", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("counts", models.JSONField(blank=True, default=dict)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("target_module", models.CharField(max_length=32)),
                ("target_type", models.CharField(blank=True, default="", max_length=64)),
                ("subject_ref", models.CharField(db_index=True, max_length=255)),
                ("subject_label", models.CharField(blank=True, default="", max_length=512)),
                ("subject_url", models.CharField(blank=True, default="", max_length=2048)),
                ("target_kind", models.CharField(max_length=64)),
                ("target_locator", models.JSONField(blank=True, default=dict)),
                ("locator_hash", models.CharField(blank=True, default="", editable=False, max_length=40)),
                ("proposed_value", models.JSONField(blank=True, default=dict)),
                ("staged_file", models.CharField(blank=True, default="", max_length=512)),
                ("current_snapshot", models.JSONField(blank=True, default=dict)),
                ("applied_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                            ("drifted", "Drifted"),
                            ("reverted", "Reverted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=128)),
                ("confidence", models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ("batch_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("external_ref", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.CharField(blank=True, default="", max_length=512)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="django_enrichment.enrichmenttask",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="enrichmenttask",
            index=models.Index(fields=["status", "type"], name="enr_task_status_type_idx"),
        ),
        migrations.AddIndex(
            model_name="contentproposal",
            index=models.Index(fields=["status", "subject_ref"], name="enr_prop_status_subj_idx"),
        ),
        migrations.AddIndex(
            model_name="contentproposal",
            index=models.Index(
                fields=["target_module", "subject_ref", "target_kind", "locator_hash"],
                name="enr_prop_target_locator_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentproposal",
            index=models.Index(fields=["status", "applied_at"], name="enr_prop_status_applied_idx"),
        ),
    ]
